### ISSUE TITLE
Multi-line messages could look better

### ISSUE THREAD

**Issue by skwerlman** [ManufacturaInd/python-zenlog#2]
For example,

``` python
import traceback
from zenlog import log
try:
    raise Exception('something is wrong')
except Exception as e:
    log.c(traceback.format_exc())
```

prints

```
   [!!!!!]  | Traceback (most recent call last):
  File "./example.py", line 4, in <module>
    if args.warranty:
Exception: something is wrong
```

It would be more readable if it printed

```
   [!!!!!]  | Traceback (most recent call last):
   [!!!!!]  |   File "./example.py", line 4, in <module>
   [!!!!!]  |     if args.warranty:
   [!!!!!]  | Exception: something is wrong
```

instead.

It should be possible to achieve this by inserting `styledname` after newlines, though there's probably a less hacky way I can't think of.

**Comment by skwerlman** [comment]
Actually, changing, for example, `critical` to

``` python
def critical(self, message, *args, **kwargs):
    for line in message.splitlines():
        self.logger.critical(line,
                             extra={"styledname": self.theme[logging.CRITICAL]},
                             *args, **kwargs)
```

achieves the same effect. I guess I'll open a PR, since this is not hacky at all.

**Comment by rlafuente** [comment]
The traceback formatting idea is great, never thought of that use case before!
